version = 2.0

../fonts/Caudex-Regular.ttf:
	fontforge -script Caudex-Regular.pe $(version)
	fontforge -script Caudex-Bold.pe $(version)
	fontforge -script Caudex-Italic.pe $(version)
	fontforge -script Caudex-BoldItalic.pe $(version)
