caudex-2.0.sfd:
        cd build
        fontforge -quiet -script caudex.pe
        fontforge -quiet -script caudexb.pe
        fontforge -quiet -script caudexi.pe
        fontforge -quiet -script caudexbi.pe

fonts:
        cd build
        fontforge -quiet -script fonts.pe

release:
        cd build
        fontforge -quiet -script release.pe
